export const languages = {
  en: {
    code: "en",
    name: "English",
    translations: {
      // Navigation
      dashboard: "Dashboard",
      animals: "Animals",
      healthRecords: "Health Records",
      vaccinations: "Vaccinations",
      breeding: "Breeding",
      maintenance: "Maintenance",
      incidents: "Incidents",
      marketplace: "Marketplace",
      users: "Users",
      alerts: "Alerts",
      sensors: "Sensors",
      settings: "Settings",
      logout: "Logout",

      // Dashboard
      welcomeBack: "Welcome back",
      totalAnimals: "Total Animals",
      breedingSuccessRate: "Breeding Success Rate",
      healthIncidents: "Health Incidents",
      activeUsers: "Active Users",
      thisMonth: "this month",
      fromLastQuarter: "from last quarter",
      fromLastMonth: "from last month",
      thisWeek: "this week",
      exportReport: "Export Report",
      addAnimal: "Add Animal",
      populationByBreed: "Population by Breed",
      distributionByBreed: "Distribution of animals by breed type",
      recentActivities: "Recent Activities",
      latestFarmActivities: "Latest farm activities and updates",
      aiRecommendations: "AI Recommendations",
      suggestedActions: "Suggested actions based on your farm data",

      // Animals
      animalManagement: "Animal Management",
      manageLivestockRecords: "Manage your livestock records",
      exportCSV: "Export CSV",
      importCSV: "Import CSV",
      animalRecords: "Animal Records",
      completeListAnimals: "Complete list of all animals with filtering and search capabilities",
      searchByTagOrBreed: "Search by Tag ID or Breed...",
      filterByBreed: "Filter by Breed",
      filterByGender: "Filter by Gender",
      allBreeds: "All Breeds",
      allGenders: "All Genders",
      male: "Male",
      female: "Female",
      tagId: "Tag ID",
      breed: "Breed",
      gender: "Gender",
      dob: "DOB",
      weight: "Weight (kg)",
      condition: "Condition",
      status: "Status",
      location: "Location",
      actions: "Actions",
      showing: "Showing",
      to: "to",
      of: "of",
      results: "results",
      previous: "Previous",
      next: "Next",

      // Add Animal Form
      addNewAnimal: "Add New Animal",
      createNewAnimalRecord: "Create a new animal record",
      backToAnimals: "Back to Animals",
      animalInformation: "Animal Information",
      fillRequiredInformation: "Fill in all the required information for the new animal",
      basicInformation: "Basic Information",
      additionalInformation: "Additional Information",
      origin: "Origin",
      acquisitionType: "Acquisition Type",
      acquisitionDate: "Acquisition Date",
      sireId: "Sire ID",
      damId: "Dam ID",
      photo: "Photo",
      notes: "Notes",
      cancel: "Cancel",
      createAnimal: "Create Animal",
      creating: "Creating...",

      // Auth
      welcomeBackAuth: "Welcome Back",
      signInToAccount: "Sign in to your Farm Home account",
      loginMethod: "Login Method",
      email: "Email",
      phone: "Phone",
      sms: "SMS",
      phoneNumber: "Phone Number",
      password: "Password",
      signingIn: "Signing in...",
      signIn: "Sign In",
      forgotPassword: "Forgot your password?",
      dontHaveAccount: "Don't have an account?",
      signUp: "Sign up",

      // Language Selection
      selectLanguage: "Select Language",
      languageUpdated: "Language updated successfully",

      // Health Records
      healthRecordsDescription: "Track and manage animal health incidents and treatments",
      addHealthRecord: "Add Health Record",
      healthRecordInformation: "Health Record Information",
      animalTagId: "Animal Tag ID",
      healthIssue: "Health Issue",
      symptoms: "Symptoms",
      diagnosis: "Diagnosis",
      treatment: "Treatment",
      veterinarian: "Veterinarian",
      treatmentDate: "Treatment Date",
      followUpDate: "Follow-up Date",
      severity: "Severity",
      cost: "Cost",
      resolved: "Resolved",
      pending: "Pending",
      critical: "Critical",
      moderate: "Moderate",
      mild: "Mild",

      // Vaccinations
      vaccinationsDescription: "Manage vaccination schedules and records",
      addVaccination: "Add Vaccination",
      vaccinationInformation: "Vaccination Information",
      vaccineName: "Vaccine Name",
      manufacturer: "Manufacturer",
      batchNumber: "Batch Number",
      expiryDate: "Expiry Date",
      administeredBy: "Administered By",
      nextDueDate: "Next Due Date",
      vaccinationType: "Vaccination Type",
      dosage: "Dosage",
      administrationRoute: "Administration Route",
      sideEffects: "Side Effects",

      // Breeding
      breedingDescription: "Track breeding activities and fertility records",
      addBreedingRecord: "Add Breeding Record",
      breedingInformation: "Breeding Information",
      sireTagId: "Sire Tag ID",
      damTagId: "Dam Tag ID",
      breedingDate: "Breeding Date",
      breedingMethod: "Breeding Method",
      expectedDelivery: "Expected Delivery Date",
      actualDelivery: "Actual Delivery Date",
      numberOfOffspring: "Number of Offspring",
      breedingNotes: "Breeding Notes",
      naturalMating: "Natural Mating",
      artificialInsemination: "Artificial Insemination",
      successful: "Successful",
      failed: "Failed",
      inProgress: "In Progress",

      // Maintenance
      maintenanceDescription: "Schedule and track routine maintenance activities",
      addMaintenanceRecord: "Add Maintenance Record",
      maintenanceInformation: "Maintenance Information",
      maintenanceType: "Maintenance Type",
      equipmentId: "Equipment ID",
      maintenanceDate: "Maintenance Date",
      performedBy: "Performed By",
      description: "Description",
      partsUsed: "Parts Used",
      laborHours: "Labor Hours",
      totalCost: "Total Cost",
      nextMaintenanceDate: "Next Maintenance Date",
      equipmentMaintenance: "Equipment Maintenance",
      facilityMaintenance: "Facility Maintenance",
      fencingRepair: "Fencing Repair",
      feedingSystemMaintenance: "Feeding System Maintenance",

      // Incidents
      incidentsDescription: "Record and track farm incidents and emergencies",
      addIncident: "Add Incident",
      incidentInformation: "Incident Information",
      incidentType: "Incident Type",
      incidentDate: "Incident Date",
      reportedBy: "Reported By",
      affectedAnimals: "Affected Animals",
      incidentDescription: "Incident Description",
      actionsTaken: "Actions Taken",
      preventiveMeasures: "Preventive Measures",
      incidentStatus: "Incident Status",
      injury: "Injury",
      illness: "Illness",
      equipment: "Equipment",
      security: "Security",
      weather: "Weather",
      other: "Other",

      // Common
      save: "Save",
      saving: "Saving...",
      edit: "Edit",
      delete: "Delete",
      view: "View",
      backTo: "Back to",
      required: "Required",
      optional: "Optional",
      selectOption: "Select an option",
      searchRecords: "Search records...",
      filterBy: "Filter by",
      sortBy: "Sort by",
      dateRange: "Date Range",
      allTypes: "All Types",
      allStatuses: "All Statuses",
      recordAdded: "Record added successfully",
      recordUpdated: "Record updated successfully",
      recordDeleted: "Record deleted successfully",

      // Milestone 2 - Analytics & Reporting
      analytics: "Analytics",
      reports: "Reports",
      notifications: "Notifications",
      mobileApp: "Mobile App",
      advancedSearch: "Advanced Search",
      realTimeData: "Real-time Data",
      dashboardAnalytics: "Dashboard Analytics",
      performanceMetrics: "Performance Metrics",
      trendAnalysis: "Trend Analysis",
      customReports: "Custom Reports",
      scheduledReports: "Scheduled Reports",
      reportTemplates: "Report Templates",
      dataVisualization: "Data Visualization",
      kpiDashboard: "KPI Dashboard",
      alertsManagement: "Alerts Management",
      notificationSettings: "Notification Settings",
      pushNotifications: "Push Notifications",
      emailAlerts: "Email Alerts",
      smsAlerts: "SMS Alerts",
      criticalAlerts: "Critical Alerts",
      systemNotifications: "System Notifications",
      userNotifications: "User Notifications",
      mobileOptimization: "Mobile Optimization",
      offlineMode: "Offline Mode",
      syncData: "Sync Data",
      fieldDataEntry: "Field Data Entry",
      qrCodeScanning: "QR Code Scanning",
      voiceInput: "Voice Input",
      photoCapture: "Photo Capture",
      gpsLocation: "GPS Location",
      weatherIntegration: "Weather Integration",
      marketPrices: "Market Prices",
      inventoryManagement: "Inventory Management",
      feedManagement: "Feed Management",
      medicineInventory: "Medicine Inventory",
      equipmentTracking: "Equipment Tracking",
      supplierManagement: "Supplier Management",
      purchaseOrders: "Purchase Orders",
      salesRecords: "Sales Records",
      financialReports: "Financial Reports",
      profitLossAnalysis: "Profit & Loss Analysis",
      cashFlowTracking: "Cash Flow Tracking",
      budgetPlanning: "Budget Planning",
      costAnalysis: "Cost Analysis",
      revenueTracking: "Revenue Tracking",
      expenseManagement: "Expense Management",
      taxReporting: "Tax Reporting",
      auditTrail: "Audit Trail",
      dataBackup: "Data Backup",
      dataRestore: "Data Restore",
      systemLogs: "System Logs",
      userActivity: "User Activity",
      securityLogs: "Security Logs",
      complianceReports: "Compliance Reports",
      regulatoryCompliance: "Regulatory Compliance",
      certificationTracking: "Certification Tracking",
      qualityAssurance: "Quality Assurance",
      traceabilityReports: "Traceability Reports",
      animalWelfare: "Animal Welfare",
      environmentalImpact: "Environmental Impact",
      sustainabilityMetrics: "Sustainability Metrics",
      carbonFootprint: "Carbon Footprint",
      waterUsage: "Water Usage",
      energyConsumption: "Energy Consumption",
      wasteManagement: "Waste Management",
      organicCertification: "Organic Certification",
      biosecurity: "Biosecurity",
      quarantineManagement: "Quarantine Management",
      diseaseOutbreakTracking: "Disease Outbreak Tracking",
      epidemiologyReports: "Epidemiology Reports",
      publicHealthReporting: "Public Health Reporting",
      veterinaryCompliance: "Veterinary Compliance",
      drugResidueTracking: "Drug Residue Tracking",
      withdrawalPeriods: "Withdrawal Periods",
      treatmentProtocols: "Treatment Protocols",
      emergencyProcedures: "Emergency Procedures",
      disasterPreparedness: "Disaster Preparedness",
      businessContinuity: "Business Continuity",
      riskAssessment: "Risk Assessment",
      insuranceClaims: "Insurance Claims",
      legalCompliance: "Legal Compliance",
      contractManagement: "Contract Management",
      laborManagement: "Labor Management",
      staffScheduling: "Staff Scheduling",
      payrollIntegration: "Payroll Integration",
      trainingRecords: "Training Records",
      certificationManagement: "Certification Management",
      performanceEvaluation: "Performance Evaluation",
      workforceAnalytics: "Workforce Analytics",
      productivityMetrics: "Productivity Metrics",
      timeTracking: "Time Tracking",
      taskManagement: "Task Management",
      workOrderManagement: "Work Order Management",
      maintenanceScheduling: "Maintenance Scheduling",
      preventiveMaintenance: "Preventive Maintenance",
      equipmentLifecycle: "Equipment Lifecycle",
      assetManagement: "Asset Management",
      depreciationTracking: "Depreciation Tracking",
      replacementPlanning: "Replacement Planning",
      vendorManagement: "Vendor Management",
      serviceContracts: "Service Contracts",
      warrantyTracking: "Warranty Tracking",
      qualityControl: "Quality Control",
      inspectionReports: "Inspection Reports",
      calibrationRecords: "Calibration Records",
      standardsCompliance: "Standards Compliance",
      processOptimization: "Process Optimization",
      efficiencyMetrics: "Efficiency Metrics",
      benchmarking: "Benchmarking",
      bestPractices: "Best Practices",
      knowledgeBase: "Knowledge Base",
      documentManagement: "Document Management",
      policyManagement: "Policy Management",
      procedureManagement: "Procedure Management",
      trainingMaterials: "Training Materials",
      operationalManuals: "Operational Manuals",
      safetyProtocols: "Safety Protocols",
      emergencyContacts: "Emergency Contacts",
      communicationTools: "Communication Tools",
      messagingSystem: "Messaging System",
      videoConferencing: "Video Conferencing",
      collaborationTools: "Collaboration Tools",
      projectManagement: "Project Management",
      milestoneTracking: "Milestone Tracking",
      resourceAllocation: "Resource Allocation",
      capacityPlanning: "Capacity Planning",
      demandForecasting: "Demand Forecasting",
      supplyChainManagement: "Supply Chain Management",
      logisticsManagement: "Logistics Management",
      transportationTracking: "Transportation Tracking",
      deliveryScheduling: "Delivery Scheduling",
      routeOptimization: "Route Optimization",
      fuelManagement: "Fuel Management",
      vehicleTracking: "Vehicle Tracking",
      maintenanceAlerts: "Maintenance Alerts",
      inspectionSchedules: "Inspection Schedules",
      complianceChecks: "Compliance Checks",
      auditSchedules: "Audit Schedules",
      reviewCycles: "Review Cycles",
      approvalWorkflows: "Approval Workflows",
      documentApproval: "Document Approval",
      changeManagement: "Change Management",
      versionControl: "Version Control",
      accessControl: "Access Control",
      permissionManagement: "Permission Management",
      roleBasedAccess: "Role-based Access",
      multiFactorAuth: "Multi-factor Authentication",
      singleSignOn: "Single Sign-On",
      passwordPolicy: "Password Policy",
      sessionManagement: "Session Management",
      encryptionSettings: "Encryption Settings",
      dataPrivacy: "Data Privacy",
      gdprCompliance: "GDPR Compliance",
      dataRetention: "Data Retention",
      rightToErasure: "Right to Erasure",
      consentManagement: "Consent Management",
      privacySettings: "Privacy Settings",
      anonymization: "Anonymization",
      pseudonymization: "Pseudonymization",
      dataMinimization: "Data Minimization",
      purposeLimitation: "Purpose Limitation",
      storageOptimization: "Storage Optimization",
      archivalPolicies: "Archival Policies",
      deletionSchedules: "Deletion Schedules",
      retentionPolicies: "Retention Policies",
      backupStrategies: "Backup Strategies",
      recoveryProcedures: "Recovery Procedures",
      disasterRecovery: "Disaster Recovery",
      businessRecovery: "Business Recovery",
      systemResilience: "System Resilience",
      failoverMechanisms: "Failover Mechanisms",
      redundancyPlanning: "Redundancy Planning",
      loadBalancing: "Load Balancing",
      performanceMonitoring: "Performance Monitoring",
      systemHealth: "System Health",
      uptimeTracking: "Uptime Tracking",
      errorMonitoring: "Error Monitoring",
      debuggingTools: "Debugging Tools",
      troubleshooting: "Troubleshooting",
      supportTickets: "Support Tickets",
      helpDesk: "Help Desk",
      userSupport: "User Support",
      technicalSupport: "Technical Support",
      customerService: "Customer Service",
      feedbackManagement: "Feedback Management",
      suggestionBox: "Suggestion Box",
      featureRequests: "Feature Requests",
      bugReporting: "Bug Reporting",
      issueTracking: "Issue Tracking",
      resolutionTracking: "Resolution Tracking",
      escalationProcedures: "Escalation Procedures",
      serviceLevel: "Service Level",
      responseTime: "Response Time",
      resolutionTime: "Resolution Time",
      customerSatisfaction: "Customer Satisfaction",
      npsScore: "NPS Score",
      usabilityTesting: "Usability Testing",
      userExperience: "User Experience",
      interfaceDesign: "Interface Design",
      accessibilityCompliance: "Accessibility Compliance",
      mobileResponsiveness: "Mobile Responsiveness",
      crossPlatformCompatibility: "Cross-platform Compatibility",
      browserCompatibility: "Browser Compatibility",
      deviceCompatibility: "Device Compatibility",
      operatingSystemSupport: "Operating System Support",
      cloudIntegration: "Cloud Integration",
      apiIntegration: "API Integration",
      thirdPartyIntegrations: "Third-party Integrations",
      dataImportExport: "Data Import/Export",
      migrationTools: "Migration Tools",
      integrationTesting: "Integration Testing",
      systemTesting: "System Testing",
      userAcceptanceTesting: "User Acceptance Testing",
      performanceTesting: "Performance Testing",
      securityTesting: "Security Testing",
      penetrationTesting: "Penetration Testing",
      vulnerabilityAssessment: "Vulnerability Assessment",
      securityAudit: "Security Audit",
      complianceAudit: "Compliance Audit",
      internalAudit: "Internal Audit",
      externalAudit: "External Audit",
      auditReports: "Audit Reports",
      findingsManagement: "Findings Management",
      correctiveActions: "Corrective Actions",
      preventiveActions: "Preventive Actions",
      continuousImprovement: "Continuous Improvement",
      processImprovement: "Process Improvement",
      qualityImprovement: "Quality Improvement",
      operationalExcellence: "Operational Excellence",
      leanManagement: "Lean Management",
      sixSigma: "Six Sigma",
      kaizen: "Kaizen",
      innovationManagement: "Innovation Management",
      researchDevelopment: "Research & Development",
      technologyAdoption: "Technology Adoption",
      digitalTransformation: "Digital Transformation",
      automationOpportunities: "Automation Opportunities",
      aiIntegration: "AI Integration",
      machineLearning: "Machine Learning",
      predictiveAnalytics: "Predictive Analytics",
      dataScience: "Data Science",
      bigDataAnalytics: "Big Data Analytics",
      businessIntelligence: "Business Intelligence",
      dataWarehouse: "Data Warehouse",
      dataLake: "Data Lake",
      etlProcesses: "ETL Processes",
      dataGovernance: "Data Governance",
      dataQuality: "Data Quality",
      masterDataManagement: "Master Data Management",
      referenceData: "Reference Data",
      metadataManagement: "Metadata Management",
      dataLineage: "Data Lineage",
      dataCatalog: "Data Catalog",
      dataDiscovery: "Data Discovery",
      selfServiceAnalytics: "Self-service Analytics",
      adhocReporting: "Ad-hoc Reporting",
      executiveDashboards: "Executive Dashboards",
      operationalDashboards: "Operational Dashboards",
      tacticalDashboards: "Tactical Dashboards",
      strategicDashboards: "Strategic Dashboards",
      scorecards: "Scorecards",
      balancedScorecard: "Balanced Scorecard",
      kpiManagement: "KPI Management",
      metricDefinition: "Metric Definition",
      targetSetting: "Target Setting",
      thresholdManagement: "Threshold Management",
      alertConfiguration: "Alert Configuration",
      escalationRules: "Escalation Rules",
      notificationRules: "Notification Rules",
      workflowAutomation: "Workflow Automation",
      processAutomation: "Process Automation",
      roboticProcessAutomation: "Robotic Process Automation",
      intelligentAutomation: "Intelligent Automation",
      cognitiveAutomation: "Cognitive Automation",
      naturalLanguageProcessing: "Natural Language Processing",
      speechRecognition: "Speech Recognition",
      imageRecognition: "Image Recognition",
      computerVision: "Computer Vision",
      augmentedReality: "Augmented Reality",
      virtualReality: "Virtual Reality",
      mixedReality: "Mixed Reality",
      iotIntegration: "IoT Integration",
      sensorData: "Sensor Data",
      telemetryData: "Telemetry Data",
      realTimeMonitoring: "Real-time Monitoring",
      edgeComputing: "Edge Computing",
      cloudComputing: "Cloud Computing",
      hybridCloud: "Hybrid Cloud",
      multiCloud: "Multi-cloud",
      containerization: "Containerization",
      microservices: "Microservices",
      serverlessComputing: "Serverless Computing",
      devopsIntegration: "DevOps Integration",
      cicdPipelines: "CI/CD Pipelines",
      infrastructureAsCode: "Infrastructure as Code",
      configurationManagement: "Configuration Management",
      environmentManagement: "Environment Management",
      releaseManagement: "Release Management",
      deploymentAutomation: "Deployment Automation",
      rollbackProcedures: "Rollback Procedures",
      blueGreenDeployment: "Blue-Green Deployment",
      canaryDeployment: "Canary Deployment",
      featureFlags: "Feature Flags",
      abTesting: "A/B Testing",
      experimentationPlatform: "Experimentation Platform",
      userSegmentation: "User Segmentation",
      personalization: "Personalization",
      recommendationEngine: "Recommendation Engine",
      contentManagement: "Content Management",
      digitalAssetManagement: "Digital Asset Management",
      brandManagement: "Brand Management",
      marketingAutomation: "Marketing Automation",
      campaignManagement: "Campaign Management",
      leadManagement: "Lead Management",
      customerRelationshipManagement: "Customer Relationship Management",
      salesForceAutomation: "Sales Force Automation",
      opportunityManagement: "Opportunity Management",
      pipelineManagement: "Pipeline Management",
      forecastingAccuracy: "Forecasting Accuracy",
      salesAnalytics: "Sales Analytics",
      customerAnalytics: "Customer Analytics",
      marketAnalytics: "Market Analytics",
      competitiveAnalysis: "Competitive Analysis",
      swotAnalysis: "SWOT Analysis",
      pestAnalysis: "PEST Analysis",
      portersFiveForces: "Porter's Five Forces",
      valueChainAnalysis: "Value Chain Analysis",
      businessModelCanvas: "Business Model Canvas",
      strategicPlanning: "Strategic Planning",
      tacticalPlanning: "Tactical Planning",
      operationalPlanning: "Operational Planning",
      scenarioPlanning: "Scenario Planning",
      contingencyPlanning: "Contingency Planning",
      riskManagement: "Risk Management",
      riskAssessmentMatrix: "Risk Assessment Matrix",
      riskMitigation: "Risk Mitigation",
      riskMonitoring: "Risk Monitoring",
      riskReporting: "Risk Reporting",
      complianceManagement: "Compliance Management",
      regulatoryReporting: "Regulatory Reporting",
      governanceFramework: "Governance Framework",
      policyFramework: "Policy Framework",
      controlFramework: "Control Framework",
      internalControls: "Internal Controls",
      segregationOfDuties: "Segregation of Duties",
      authorizationMatrix: "Authorization Matrix",
      approvalLimits: "Approval Limits",
      delegationOfAuthority: "Delegation of Authority",
      conflictOfInterest: "Conflict of Interest",
      ethicsManagement: "Ethics Management",
      codeOfConduct: "Code of Conduct",
      whistleblowerProtection: "Whistleblower Protection",
      fraudDetection: "Fraud Detection",
      fraudPrevention: "Fraud Prevention",
      antiCorruption: "Anti-corruption",
      antiMoneyLaundering: "Anti-money Laundering",
      sanctionsCompliance: "Sanctions Compliance",
      exportControls: "Export Controls",
      importRegulations: "Import Regulations",
      customsCompliance: "Customs Compliance",
      tradeCompliance: "Trade Compliance",
      internationalRegulations: "International Regulations",
      localRegulations: "Local Regulations",
      industryStandards: "Industry Standards",
      certificationRequirements: "Certification Requirements",
      accreditationManagement: "Accreditation Management",
      qualityManagementSystem: "Quality Management System",
      environmentalManagementSystem: "Environmental Management System",
      healthSafetyManagementSystem: "Health & Safety Management System",
      informationSecurityManagementSystem: "Information Security Management System",
      businessContinuityManagementSystem: "Business Continuity Management System",
      riskManagementSystem: "Risk Management System",
      complianceManagementSystem: "Compliance Management System",
      integratedManagementSystem: "Integrated Management System",
      managementSystemAudit: "Management System Audit",
      certificationAudit: "Certification Audit",
      surveillanceAudit: "Surveillance Audit",
      recertificationAudit: "Recertification Audit",
      nonConformityManagement: "Non-conformity Management",
      correctiveActionManagement: "Corrective Action Management",
      preventiveActionManagement: "Preventive Action Management",
      managementReview: "Management Review",
      executiveReview: "Executive Review",
      boardReporting: "Board Reporting",
      stakeholderReporting: "Stakeholder Reporting",
      investorRelations: "Investor Relations",
      publicRelations: "Public Relations",
      mediaRelations: "Media Relations",
      communityRelations: "Community Relations",
      governmentRelations: "Government Relations",
      regulatorRelations: "Regulator Relations",
      industryAssociations: "Industry Associations",
      professionalNetworks: "Professional Networks",
      partnershipManagement: "Partnership Management",
      allianceManagement: "Alliance Management",
      jointVentureManagement: "Joint Venture Management",
      mergerAcquisitionIntegration: "Merger & Acquisition Integration",
      divestitureManagement: "Divestiture Management",
      spinoffManagement: "Spinoff Management",
      corporateRestructuring: "Corporate Restructuring",
      organizationalDesign: "Organizational Design",
      changeManagementProgram: "Change Management Program",
      transformationProgram: "Transformation Program",
      culturalTransformation: "Cultural Transformation",
      leadershipDevelopment: "Leadership Development",
      talentManagement: "Talent Management",
      successionPlanning: "Succession Planning",
      careerDevelopment: "Career Development",
      skillsManagement: "Skills Management",
      competencyManagement: "Competency Management",
      learningManagement: "Learning Management",
      knowledgeManagement: "Knowledge Management",
      intellectualPropertyManagement: "Intellectual Property Management",
      patentManagement: "Patent Management",
      trademarkManagement: "Trademark Management",
      copyrightManagement: "Copyright Management",
      tradesecretManagement: "Trade Secret Management",
      licensingManagement: "Licensing Management",
      royaltyManagement: "Royalty Management",
      technologyTransfer: "Technology Transfer",
      innovationPortfolio: "Innovation Portfolio",
      rdPortfolio: "R&D Portfolio",
      productPortfolio: "Product Portfolio",
      servicePortfolio: "Service Portfolio",
      brandPortfolio: "Brand Portfolio",
      assetPortfolio: "Asset Portfolio",
      investmentPortfolio: "Investment Portfolio",
      portfolioOptimization: "Portfolio Optimization",
      capitalAllocation: "Capital Allocation",
      resourceOptimization: "Resource Optimization",
      costOptimization: "Cost Optimization",
      revenueOptimization: "Revenue Optimization",
      profitOptimization: "Profit Optimization",
      valueOptimization: "Value Optimization",
      performanceOptimization: "Performance Optimization",
      operationalOptimization: "Operational Optimization",
      strategicOptimization: "Strategic Optimization",
      tacticalOptimization: "Tactical Optimization",
      continuousOptimization: "Continuous Optimization",
    },
  },
  ur: {
    code: "ur",
    name: "اردو",
    translations: {
      // Navigation
      dashboard: "ڈیش بورڈ",
      animals: "جانور",
      healthRecords: "صحت کے ریکارڈ",
      vaccinations: "ٹیکے",
      breeding: "پیدائش",
      maintenance: "دیکھ بھال",
      incidents: "واقعات",
      marketplace: "مارکیٹ",
      users: "صارفین",
      alerts: "الرٹس",
      sensors: "سینسرز",
      settings: "ترتیبات",
      logout: "لاگ آؤٹ",

      // Dashboard
      welcomeBack: "خوش آمدید",
      totalAnimals: "کل جانور",
      breedingSuccessRate: "پیدائش کی کامیابی کی شرح",
      healthIncidents: "صحت کے واقعات",
      activeUsers: "فعال صارفین",
      thisMonth: "اس مہینے",
      fromLastQuarter: "گزشتہ سہ ماہی سے",
      fromLastMonth: "گزشتہ مہینے سے",
      thisWeek: "اس ہفتے",
      exportReport: "رپورٹ برآمد کریں",
      addAnimal: "جانور شامل کریں",
      populationByBreed: "نسل کے لحاظ سے آبادی",
      distributionByBreed: "نسل کی قسم کے لحاظ سے جانوروں کی تقسیم",
      recentActivities: "حالیہ سرگرمیاں",
      latestFarmActivities: "تازہ ترین فارم کی سرگرمیاں اور اپ ڈیٹس",
      aiRecommendations: "AI سفارشات",
      suggestedActions: "آپ کے فارم ڈیٹا کی بنیاد پر تجویز کردہ اقدامات",

      // Animals
      animalManagement: "جانوروں کا انتظام",
      manageLivestockRecords: "اپنے مویشیوں کے ریکارڈز کا انتظام کریں",
      exportCSV: "CSV برآمد کریں",
      importCSV: "CSV درآمد کریں",
      animalRecords: "جانوروں کے ریکارڈ",
      completeListAnimals: "فلٹرنگ اور تلاش کی صلاحیتوں کے ساتھ تمام جانوروں کی مکمل فہرست",
      searchByTagOrBreed: "ٹیگ ID یا نسل سے تلاش کریں...",
      filterByBreed: "نسل سے فلٹر کریں",
      filterByGender: "جنس سے فلٹر کریں",
      allBreeds: "تمام نسلیں",
      allGenders: "تمام جنس",
      male: "مرد",
      female: "عورت",
      tagId: "ٹیگ ID",
      breed: "نسل",
      gender: "جنس",
      dob: "تاریخ پیدائش",
      weight: "وزن (کلو)",
      condition: "حالت",
      status: "حالت",
      location: "مقام",
      actions: "اعمال",
      showing: "دکھا رہا ہے",
      to: "سے",
      of: "کا",
      results: "نتائج",
      previous: "پچھلا",
      next: "اگلا",

      // Add Animal Form
      addNewAnimal: "نیا جانور شامل کریں",
      createNewAnimalRecord: "ایک نیا جانور کا ریکارڈ بنائیں",
      backToAnimals: "جانوروں پر واپس",
      animalInformation: "جانور کی معلومات",
      fillRequiredInformation: "نیا جانور کے لیے تمام ضروری معلومات بھریں",
      basicInformation: "بنیادی معلومات",
      additionalInformation: "اضافی معلومات",
      origin: "اصل",
      acquisitionType: "حصول کی قسم",
      acquisitionDate: "حصول کی تاریخ",
      sireId: "باپ ID",
      damId: "ماں ID",
      photo: "تصویر",
      notes: "نوٹس",
      cancel: "منسوخ کریں",
      createAnimal: "جانور بنائیں",
      creating: "بنایا جا رہا ہے...",

      // Auth
      welcomeBackAuth: "خوش آمدید",
      signInToAccount: "اپنے فارم ہوم اکاؤنٹ میں سائن ان کریں",
      loginMethod: "لاگ ان کا طریقہ",
      email: "ای میل",
      phone: "فون",
      sms: "SMS",
      phoneNumber: "فون نمبر",
      password: "پاس ورڈ",
      signingIn: "سائن ان ہو رہا ہے...",
      signIn: "سائن ان",
      forgotPassword: "کیا آپ اپنا پاس ورڈ بھول گئے؟",
      dontHaveAccount: "کیا آپ کا اکاؤنٹ نہیں ہے؟",

      // Health Records
      healthRecordsDescription: "جانوروں کی صحت کے واقعات اور علاج کا ٹریک اور انتظام کریں",
      addHealthRecord: "صحت کا ریکارڈ شامل کریں",
      healthRecordInformation: "صحت کے ریکارڈ کی معلومات",
      animalTagId: "جانور کا ٹیگ ID",
      healthIssue: "صحت کا مسئلہ",
      symptoms: "علامات",
      diagnosis: "تشخیص",
      treatment: "علاج",
      veterinarian: "جانوروں کا ڈاکٹر",
      treatmentDate: "علاج کی تاریخ",
      followUpDate: "فالو اپ کی تاریخ",
      severity: "شدت",
      cost: "لاگت",
      resolved: "حل شدہ",
      pending: "زیر التواء",
      critical: "تشویشناک",
      moderate: "درمیانی",
      mild: "ہلکا",

      // Vaccinations
      vaccinationsDescription: "ٹیکے لگانے کے شیڈول اور ریکارڈز کا انتظام کریں",
      addVaccination: "ٹیکا شامل کریں",
      vaccinationInformation: "ٹیکے کی معلومات",
      vaccineName: "ٹیکے کا نام",
      manufacturer: "تیار کنندہ",
      batchNumber: "بیچ نمبر",
      expiryDate: "ختم ہونے کی تاریخ",
      administeredBy: "کس نے دیا",
      nextDueDate: "اگلی تاریخ",
      vaccinationType: "ٹیکے کی قسم",
      dosage: "خوری",
      administrationRoute: "دینے کا راستہ",
      sideEffects: "مضر اثرات",

      // Breeding
      breedingDescription: "پیدائش کی سرگرمیوں اور زرخیزی کے ریکارڈز کا ٹریک کریں",
      addBreedingRecord: "پیدائش کا ریکارڈ شامل کریں",
      breedingInformation: "پیدائش کی معلومات",
      sireTagId: "باپ کا ٹیگ ID",
      damTagId: "ماں کا ٹیگ ID",
      breedingDate: "پیدائش کی تاریخ",
      breedingMethod: "پیدائش کا طریقہ",
      expectedDelivery: "متوقع ڈیلیوری کی تاریخ",
      actualDelivery: "اصل ڈیلیوری کی تاریخ",
      numberOfOffspring: "اولاد کی تعداد",
      breedingNotes: "پیدائش کے نوٹس",
      naturalMating: "قدرتی ملاپ",
      artificialInsemination: "مصنوعی انسیمنیشن",
      successful: "کامیاب",
      failed: "ناکام",
      inProgress: "جاری",

      // Maintenance
      maintenanceDescription: "روٹین دیکھ بھال کی سرگرمیوں کا شیڈول اور ٹریک کریں",
      addMaintenanceRecord: "دیکھ بھال کا ریکارڈ شامل کریں",
      maintenanceInformation: "دیکھ بھال کی معلومات",
      maintenanceType: "دیکھ بھال کی قسم",
      equipmentId: "سامان ID",
      maintenanceDate: "دیکھ بھال کی تاریخ",
      performedBy: "کس نے کیا",
      description: "تفصیل",
      partsUsed: "استعمال شدہ حصے",
      laborHours: "مزدوری کے گھنٹے",
      totalCost: "کل لاگت",
      nextMaintenanceDate: "اگلی دیکھ بھال کی تاریخ",
      equipmentMaintenance: "سامان کی دیکھ بھال",
      facilityMaintenance: "سہولت کی دیکھ بھال",
      fencingRepair: "باڑ کی مرمت",
      feedingSystemMaintenance: "کھلانے کے نظام کی دیکھ بھال",

      // Incidents
      incidentsDescription: "فارم کے واقعات اور ایمرجنسیز کو ریکارڈ اور ٹریک کریں",
      addIncident: "واقعہ شامل کریں",
      incidentInformation: "واقعے کی معلومات",
      incidentType: "واقعے کی قسم",
      incidentDate: "واقعے کی تاریخ",
      reportedBy: "کس نے رپورٹ کیا",
      affectedAnimals: "متاثرہ جانور",
      incidentDescription: "واقعے کی تفصیل",
      actionsTaken: "اٹھائے گئے اقدامات",
      preventiveMeasures: "احتیاطی تدابیر",
      incidentStatus: "واقعے کی حالت",
      injury: "زخم",
      illness: "بیماری",
      equipment: "سامان",
      security: "سیکیورٹی",
      weather: "موسم",
      other: "دیگر",

      // Common
      save: "محفوظ کریں",
      saving: "محفوظ کیا جا رہا ہے...",
      edit: "ترمیم",
      delete: "حذف کریں",
      view: "دیکھیں",
      backTo: "واپس",
      required: "ضروری",
      optional: "اختیاری",
      selectOption: "ایک آپشن منتخب کریں",
      searchRecords: "ریکارڈز تلاش کریں...",
      filterBy: "فلٹر کریں",
      sortBy: "ترتیب دیں",
      dateRange: "تاریخ کی حد",
      allTypes: "تمام اقسام",
      allStatuses: "تمام حالتیں",
      recordAdded: "ریکارڈ کامیابی سے شامل کیا گیا",
      recordUpdated: "ریکارڈ کامیابی سے اپ ڈیٹ کیا گیا",
      recordDeleted: "ریکارڈ کامیابی سے حذف کیا گیا",
      selectLanguage: "زبان منتخب کریں",
      languageUpdated: "زبان کامیابی سے اپ ڈیٹ ہو گئی",
    },
  },
}

export type LanguageCode = keyof typeof languages
export type TranslationKey = {
  [K in keyof typeof languages.en.translations]: K extends string ? K : never;
}[keyof typeof languages.en.translations];
